"""Regression tests for DeltaSigmaPrj.

Pins:
1. Default ``__call__`` returns the cl+LSS correlation-excess piece.
2. RND+CL algebra identity in the decomposition.
3. n_theta_per_seg convergence plateau.
4. Full ``total`` at default (n_per_seg=30) matches a scipy.quad reference
   from ``validations/delta_sigma_prj_diagnostics.py`` to 0.5%.
5. The adaptive ``R_max_cMpch`` rule agrees with the explicit 30-cMpc/h
   choice on the ``cl`` piece (Section 3 of the DeltaSigma derivation
   note).
6. Per-R theta breakpoint rule.
"""
from __future__ import annotations
import os
import numpy as np
import pytest

from richness_selection import DeltaSigmaPrj


REF_R = np.array([0.3, 1.0, 3.0, 10.0])

# scipy.quad reference generated by
#   validations/delta_sigma_prj_diagnostics.py
# at (lob=20, zob=0.5), same conventions as the production DeltaSigmaPrj.
# Values filled in once the reference CSV is produced; see
# validations/cache/delta_sigma_prj_quad_ref.md for the source.
REF_QUAD_CL = None     # filled via fixture below
REF_QUAD_TOTAL = None


def _load_quad_ref():
    """Load the scipy.quad reference table if it exists.

    Returns (total, cl) arrays aligned with ``REF_R``, or (None, None)
    if the reference CSV has not been generated (skip the quad test).
    """
    path = os.path.join(
        os.path.dirname(__file__), "..",
        "validations", "cache", "delta_sigma_prj_quad_ref.csv")
    if not os.path.exists(path):
        return None, None
    total = np.zeros_like(REF_R)
    cl = np.zeros_like(REF_R)
    with open(path) as f:
        next(f)  # header
        rows = [row.strip().split(",") for row in f if row.strip()]
    for iR, R in enumerate(REF_R):
        for row in rows:
            if abs(float(row[2]) - R) < 1e-6:
                total[iR] = float(row[3])
                cl[iR] = float(row[5])
                break
        else:
            return None, None
    return total, cl


@pytest.fixture(scope="module")
def dsp(cosmo, sel_bias, nfw):
    """Default DeltaSigmaPrj: adaptive R_max = 3 * max(R)."""
    return DeltaSigmaPrj(cosmo, sel_bias, nfw, n_theta_per_seg=30)


@pytest.fixture(scope="module")
def dsp_R30(cosmo, sel_bias, nfw):
    """DeltaSigmaPrj pinned to R_max = 30 cMpc/h for quad comparison."""
    return DeltaSigmaPrj(cosmo, sel_bias, nfw, n_theta_per_seg=30,
                         R_max_cMpch=30.0)


def test_default_returns_cl(dsp):
    cl_default = dsp(REF_R, 20.0, 0.5)
    dec = dsp(REF_R, 20.0, 0.5, return_decomposition=True)
    np.testing.assert_allclose(cl_default, dec["cl"], rtol=0, atol=0)
    np.testing.assert_allclose(dec["rnd"] + dec["cl"], dec["total"],
                               rtol=0, atol=0)
    # cl piece is positive and smaller than total at this lob, zob.
    assert (dec["cl"] > 0).all()


def test_total_vs_scipy_quad(dsp_R30):
    """`total` at n_per_seg=30, R_max=30 matches scipy.quad.

    We pin R_max=30 to match the quad reference conventions in
    ``validations/delta_sigma_prj_diagnostics.py`` (same R_max_cMpch).

    Tolerance is 0.5% on R >= 1 cMpc/h, relaxed to 2.5% at R = 0.3
    cMpc/h.  At R=0.3 the exclusion angle theta_excl(z) sits very close
    to theta_R = R/D_A(z_ob), and the [1 + b b_sel xi] bracket changes
    amplitude sharply across the breakpoint; scipy.quad's adaptive
    refinement there issues an IntegrationWarning and settles ~2% above
    the GL-on-segments answer.  Cross-check: tightening the quad
    tolerances from (3e-3, 1e-2) to (1e-3, 3e-3) changes the quad
    answer by <0.01% (so the quad is self-converged), and
    ``test_n_per_seg_convergence`` shows the production ``cl`` is
    converged to <0.5% between ``n_per_seg=30`` and ``120``.  The
    residual 2% gap is therefore a real quadrature-method difference at
    this smallest R, not a bug in either side.
    """
    ref_total, ref_cl = _load_quad_ref()
    if ref_total is None:
        pytest.skip("quad reference CSV not generated; run "
                    "validations/delta_sigma_prj_diagnostics.py first")
    dec = dsp_R30(REF_R, 20.0, 0.5, return_decomposition=True)
    rel_total = np.abs(dec["total"] - ref_total) / np.abs(ref_total)
    rel_cl = np.abs(dec["cl"] - ref_cl) / np.abs(ref_cl)
    # Per-R tolerance: relax at R=0.3 (see docstring).
    tol = np.where(REF_R < 0.5, 2.5e-2, 5e-3)
    assert (rel_total < tol).all(), (
        f"Relative errors on total exceed per-R tolerance.\n"
        f"total = {dec['total']}\nref   = {ref_total}\n"
        f"rel   = {rel_total}\ntol   = {tol}"
    )
    assert (rel_cl < tol).all(), (
        f"Relative errors on cl exceed per-R tolerance.\n"
        f"cl    = {dec['cl']}\nref   = {ref_cl}\n"
        f"rel   = {rel_cl}\ntol   = {tol}"
    )


def test_n_per_seg_convergence(cosmo, sel_bias, nfw):
    dsp30 = DeltaSigmaPrj(cosmo, sel_bias, nfw, n_theta_per_seg=30)
    dsp120 = DeltaSigmaPrj(cosmo, sel_bias, nfw, n_theta_per_seg=120)
    v30 = dsp30(REF_R, 20.0, 0.5, return_decomposition=True)["cl"]
    v120 = dsp120(REF_R, 20.0, 0.5, return_decomposition=True)["cl"]
    rel = np.abs(v30 - v120) / np.abs(v120)
    assert rel.max() < 5e-3, (
        f"n_per_seg=30 vs 120 disagree by {rel.max():.3%} on cl; "
        f"default grid is not converged."
    )


def test_adaptive_Rmax_agrees_with_legacy(cosmo, sel_bias, nfw):
    """Adaptive R_max = 3 * max(R) should give the same ``cl`` as the
    legacy R_max = 30 cMpc/h at max(R) = 10 cMpc/h (both give R_max=30).

    Section 3 of docs/delta_sigma_prj_derivation.tex: DeltaSigma_mis
    dies for R_mis >> R, so the cl piece is insensitive to the outer
    theta truncation as long as theta_max >~ 3 * theta_R_max.
    """
    dsp_adaptive = DeltaSigmaPrj(cosmo, sel_bias, nfw)    # adaptive
    dsp_legacy = DeltaSigmaPrj(cosmo, sel_bias, nfw, R_max_cMpch=30.0)
    cl_a = dsp_adaptive(REF_R, 20.0, 0.5)
    cl_l = dsp_legacy(REF_R, 20.0, 0.5)
    # max(R) = 10, so R_max_adaptive = 30 = R_max_legacy -- results
    # should agree to floating point (modulo breakpoint-set de-dup
    # differences at the theta_max end).
    rel = np.abs(cl_a - cl_l) / np.abs(cl_l)
    assert rel.max() < 1e-3, (
        f"adaptive vs legacy R_max disagree by {rel.max():.3%} on cl at "
        f"max(R)=10; something is wrong with the adaptive plumbing.\n"
        f"adaptive: {cl_a}\nlegacy  : {cl_l}"
    )


def test_theta_grid_breakpoints_include_each_R(dsp):
    """Each requested R must appear as a theta_R breakpoint."""
    dec = dsp(REF_R, 20.0, 0.5, return_decomposition=True)
    brk = dec["theta_info"]["breakpoints"]
    D_A_o = dsp.cosmo.D_A(0.5)
    theta_Rs = REF_R / D_A_o
    for tR in theta_Rs:
        assert np.any(np.abs(brk - tR) / tR < 1e-6), (
            f"theta_R = {tR:.3e} missing from breakpoints {brk}"
        )


def test_adaptive_theta_max_scales_with_R(cosmo, sel_bias, nfw):
    """Adaptive rule: theta_max = 3 * max(R) / chi(zob) (Section 3)."""
    dsp = DeltaSigmaPrj(cosmo, sel_bias, nfw)
    R_small = np.array([0.3, 1.0, 3.0])
    R_large = np.array([0.3, 1.0, 3.0, 10.0])
    dec_s = dsp(R_small, 20.0, 0.5, return_decomposition=True)
    dec_l = dsp(R_large, 20.0, 0.5, return_decomposition=True)
    # theta_max scales linearly with max(R).
    ratio = dec_l["theta_info"]["theta_max"] / dec_s["theta_info"]["theta_max"]
    assert abs(ratio - (10.0 / 3.0)) < 1e-6, (
        f"theta_max ratio {ratio} != max(R) ratio 10/3")
