"""Regenerate the miscentered DeltaSigma lookup table, SIGNED, in
linear space -- the drop-in replacement for y3_cluster_cpp's
``table_1000_1e-03_5e+03_log_deltasigma_single.txt`` (whose ln-storage
floors the negative branch DeltaSigma_mis(R < R_mis) < 0 and thereby
inflates the two-halo cl piece ~1.5x and breaks the rnd cancellation).

Writes ``table_1000_1e-03_5e+03_deltasigma_signed.txt`` next to the
shipped tables (RICHNESS_SELECTION_NFW_DIR): rows = the shipped
ln(x_mis) axis, columns = a dense ln(x) axis written alongside as
``table_1000_1e-03_5e+03_deltasigma_signed_logx.txt``.  Values are the
dimensionless signed excess in units of ``2 r_s rho_s`` (same
prefactor convention as the Sigma table), computed with the analytic
CLensPy closed form (see nfw._build_signed_dsigma_spline).

Run:  RICHNESS_SELECTION_NFW_DIR=... python scripts/regenerate_deltasigma_table.py
"""
import os
import sys

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                "..", "src"))

from richness_selection import Cosmology, NFWMiscentered  # noqa: E402

TABLE_DIR = os.environ["RICHNESS_SELECTION_NFW_DIR"]
N_X = 1000

def main():
    cosmo = Cosmology()
    nfw = NFWMiscentered(cosmo, table_dir=TABLE_DIR)
    # Same axes as the shipped log_sigma table, so the file is a strict
    # drop-in next to single_logx.txt / single_logxmis.txt (the name and
    # shape the y3_cluster_cpp signed-table reader expects).
    n_xmis = nfw._dsig_spl.get_knots()[0].size
    lnxmis = nfw._log_xmis[:n_xmis]
    lnx = nfw._log_x[:N_X]
    spl = nfw._build_signed_dsigma_spline(lnxmis)
    gs = spl(lnxmis, lnx)
    header = ("signed miscentered DeltaSigma table: dimensionless excess "
              "gs(x | x_mis) in units of 2*r_s*rho_s (LINEAR space, "
              "negative branch retained -- read WITHOUT exp).  rows: "
              "shipped single_logxmis axis; cols: shipped single_logx "
              "axis.  Generated by richness_selection "
              "nfw._build_signed_dsigma_spline (CLensPy closed form: "
              "by-parts aperture-mass identity, law-of-cosines nodes).")
    out = os.path.join(
        TABLE_DIR, "table_1000_1e-03_5e+03_deltasigma_signed_single.txt")
    np.savetxt(out, gs, header=header)
    print(f"wrote signed table {gs.shape} -> {out}")
    # sanity: negative branch present, centered row positive
    print(f"  min={gs.min():+.3e}  max={gs.max():+.3e}  "
          f"neg fraction={np.mean(gs < 0):.2%}")

if __name__ == "__main__":
    main()
