"""Regenerate the miscentered DeltaSigma lookup table, SIGNED, in
linear space -- the drop-in replacement for y3_cluster_cpp's
``table_1000_1e-03_5e+03_log_deltasigma_single.txt`` (whose ln-storage
floors the negative branch DeltaSigma_mis(R < R_mis) < 0 and thereby
inflates the two-halo cl piece ~1.5x and breaks the rnd cancellation).

Writes ``table_1000_1e-03_5e+03_deltasigma_signed.txt`` next to the
shipped tables (RICHNESS_SELECTION_NFW_DIR): rows = the shipped
ln(x_mis) axis, columns = a dense ln(x) axis written alongside as
``table_1000_1e-03_5e+03_deltasigma_signed_logx.txt``.  Values are the
dimensionless signed excess in units of ``2 r_s rho_s`` (same
prefactor convention as the Sigma table), computed with the analytic
CLensPy closed form (see nfw._build_signed_dsigma_spline).

Run:  RICHNESS_SELECTION_NFW_DIR=... python scripts/regenerate_deltasigma_table.py
"""
import os
import sys

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                "..", "src"))

from richness_selection import Cosmology, NFWMiscentered  # noqa: E402

TABLE_DIR = os.environ["RICHNESS_SELECTION_NFW_DIR"]
N_X = 1000

def main():
    cosmo = Cosmology()
    nfw = NFWMiscentered(cosmo, table_dir=TABLE_DIR)
    lnxmis = nfw._log_xmis[: nfw._dsig_spl.get_knots()[0].size]
    lnx = np.linspace(nfw._lnx_lo, nfw._lnx_hi, N_X)
    spl = nfw._build_signed_dsigma_spline(lnxmis, n_dense=N_X)
    gs = spl(lnxmis, lnx)
    header = ("signed miscentered DeltaSigma table: dimensionless excess "
              "gs(x | x_mis) in units of 2*r_s*rho_s (LINEAR space, "
              "negative branch retained).  rows: shipped ln(x_mis) axis; "
              "cols: ln(x) axis in *_logx.txt.  Generated by "
              "richness_selection nfw._build_signed_dsigma_spline "
              "(CLensPy closed form).")
    np.savetxt(os.path.join(
        TABLE_DIR, "table_1000_1e-03_5e+03_deltasigma_signed.txt"),
        gs, header=header)
    np.savetxt(os.path.join(
        TABLE_DIR, "table_1000_1e-03_5e+03_deltasigma_signed_logx.txt"),
        lnx, header="ln(x) axis for deltasigma_signed table")
    print(f"wrote signed table {gs.shape} to {TABLE_DIR}")

if __name__ == "__main__":
    main()
